sudo: false
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - travis_retry composer install
  - sudo locale-gen --no-purge --lang nl_NL.UTF-8
  - sudo locale-gen --no-purge --lang pt_BR.UTF-8
  - sudo locale-gen --no-purge --lang ru_RU.UTF-8
  - pecl install uopz || echo "Cound not install uopz" 1>&2

script:
  - vendor/bin/phpunit --testsuite=unit --verbose --colors
  - vendor/bin/phpunit --testsuite=integration --verbose --colors

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Quality assurance
      env: CODE_COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script: vendor/bin/phpunit --coverage-clover ./clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Quality assurance
      env: DOCHEADER
      install: travis_retry composer install
      script: vendor/bin/docheader check library/ tests/

    - stage: Quality assurance
      env: CODE_STANDARD
      install: travis_retry composer install
      script: vendor/bin/phpcs

    - stage: Quality assurance
      env: STATIC_ANALYSIS
      install: travis_retry composer install
      script: vendor/bin/phpstan analyze
