name: Update Regional Information

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-regional-information:
    name: Update Regional Information

    runs-on: ubuntu-latest

    steps:
      - name: Install xmlstarlet
        run: sudo apt install xmlstarlet idn2

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ secrets.LAST_MINOR_VERSION }}

      - name: Update top level domains
        run: bin/update-domain-toplevel

      - name: Update public domain suffixes
        run: bin/update-domain-suffixes

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          commit-message: Update Regional Information
          title: Update Regional Information
          base: ${{ secrets.LAST_MINOR_VERSION }}
          branch: "workflows/update-regional-information"

      - name: Enable auto-merge for PR
        if: steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
