name: Update Regional Information

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-regional-information:
    name: Update Regional Information

    runs-on: ubuntu-latest

    steps:
      - name: Install xmlstarlet
        run: sudo apt install xmlstarlet

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ secrets.LAST_MINOR_VERSION }}

      - name: Update currency codes
        run: bin/update-currency-codes

      - name: Update language codes 
        run: bin/update-language-codes

      - name: Update top level domains
        run: bin/update-domain-toplevel

      - name: Update public domain suffixes
        run: bin/update-domain-suffixes

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          commit-message: Update Regional Information
          title: Update Regional Information
          base: ${{ secrets.LAST_MINOR_VERSION }}
          branch: "workflows/update-regional-information"
