name: Update language codes

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  update-language-codes:
    name: Update language codes

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.LAST_MINOR_VERSION }}

      - name: Execute script
        run: bin/update-language-codes

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          commit-message: Update list of language codes
          title: Update list of language codes
          base: ${{ secrets.LAST_MINOR_VERSION }}
          branch: "workflows/update-language-codes"
